CREATE TABLE `obj_customer` (
	`id` INT(10) UNSIGNED NOT NULL,
	`objectType` VARCHAR(255) NOT NULL,
	`data` LONGBLOB NOT NULL,
	`prop_id` INT(10) UNSIGNED NULL DEFAULT NULL,
	`prop_populationregistrynumber` VARCHAR(255) NOT NULL DEFAULT '',
	`prop_firstname` VARCHAR(255) NOT NULL DEFAULT '',
	`prop_lastname` VARCHAR(255) NOT NULL DEFAULT '',
	`prop_username` VARCHAR(255) NOT NULL DEFAULT '',
	`prop_century` INT(10) UNSIGNED NULL DEFAULT NULL,
	`prop_classified` TINYINT(4) NULL DEFAULT NULL,
	`prop_groupcustomer` TINYINT(4) NULL DEFAULT NULL,
	`prop_customernumber` VARCHAR(255) NOT NULL DEFAULT '',
	`prop_homeaddress` VARCHAR(255) NOT NULL DEFAULT '',
	`prop_homeaddressobj` INT(10) UNSIGNED NULL DEFAULT NULL,
	`prop_homeaddressobj_objname` VARCHAR(255) NOT NULL DEFAULT '',
	`prop_county` VARCHAR(255) NOT NULL DEFAULT '',
	`prop_muni` VARCHAR(255) NOT NULL DEFAULT '',
	`prop__muniid` INT(10) UNSIGNED NULL DEFAULT NULL,
	`prop__muniid_objname` VARCHAR(255) NOT NULL DEFAULT '',
	`prop_zipcode` VARCHAR(255) NOT NULL DEFAULT '',
	`prop_homecity` VARCHAR(255) NOT NULL DEFAULT '',
	`prop_updatefromregautomatically` TINYINT(4) NULL DEFAULT NULL,
	`prop_customercards` TEXT NULL,
	`prop_deceaseddate` DATETIME NULL DEFAULT NULL,
	`prop__districtid` INT(10) UNSIGNED NULL DEFAULT NULL,
	`prop__districtid_objname` VARCHAR(255) NOT NULL DEFAULT '',
	`prop__actorrole` INT(10) UNSIGNED NULL DEFAULT NULL,
	`prop__actorrole_objname` VARCHAR(255) NOT NULL DEFAULT '',
	`prop_currentcontactitem_data` VARCHAR(255) NOT NULL DEFAULT '',
	`prop_defaultcontactitem_data` VARCHAR(255) NOT NULL DEFAULT '',
	`prop_language` INT(10) UNSIGNED NULL DEFAULT NULL,
	`prop_language_objname` VARCHAR(255) NOT NULL DEFAULT '',
	`prop_deleted` TINYINT(4) NULL DEFAULT NULL,
	`prop_deletedtime` DATETIME NULL DEFAULT NULL,
	`prop_objectname` VARCHAR(255) NOT NULL DEFAULT '',
	`prop_objectbasename` VARCHAR(255) NOT NULL DEFAULT '',
	PRIMARY KEY (`id`),
	INDEX `prop_populationregistrynumber` (`prop_populationregistrynumber`),
	INDEX `prop_firstname` (`prop_firstname`),
	INDEX `prop_lastname` (`prop_lastname`),
	INDEX `prop_username` (`prop_username`),
	INDEX `prop_customernumber` (`prop_customernumber`)
)
COLLATE='latin1_swedish_ci'
ENGINE=InnoDB
;
